### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Calistrea** [teagan75/Teagans-Guide-to-the-Galaxy#2]
more planets crashes the mod pack before I can even get it open. 
[fml-client-latest.txt](https://github.com/teagan75/Galactic-Pioneer/files/649658/fml-client-latest.txt)

**Comment by teagan75** [comment]
Sorry about that. The updated Galacticraft builds did not make it into the pack on the launcher. i just pushed an update that should fix the crash.
