### ISSUE TITLE
nate larson odd black green and purple things that block vision

### ISSUE THREAD

**Issue by DrunkenCocroach** [teagan75/Teagans-Guide-to-the-Galaxy#5]
![2017-05-31_12 16 52](https://cloud.githubusercontent.com/assets/29103291/26644676/26e57734-45fb-11e7-983f-552b33911e75.png)
![2017-05-31_12 17 03](https://cloud.githubusercontent.com/assets/29103291/26644679/283a3dae-45fb-11e7-8915-4f4c1a26b7da.png)

I talked to teagen about it and she said to put it here
![2017-05-31_12 08 33](https://cloud.githubusercontent.com/assets/29103291/26644579/d64f1654-45fa-11e7-9cfd-34015b1cafd3.png)
![2017-05-31_12 08 34](https://cloud.githubusercontent.com/assets/29103291/26644580/d7e96afa-45fa-11e7-8d9e-ad919b36994f.png)

**Comment by teagan75** [comment]
You can try pressing F3+A to refresh the renderers or you don't have enough ram allocated to the game. Other than those two, I don't know what else could be causing it.

**Comment by teagan75** [comment]
Was this issue resolved?

**Comment by DrunkenCocroach** [comment]
no

**Comment by DrunkenCocroach** [comment]
my PC broke so I can't play anymore thank you for trying to help
